spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password:
  jpa:
    hibernate:
      ddl-auto: create
      h2:
        console:
          enabled: true
---
redis:
  database:
  password:
  host:
  port:
---
environment:
redis:
  host: Vit
  port: 8080
  password: Password!